service: movies-service
frameworkVersion: '4'

plugins:
  - serverless-python-requirements

custom:
  variables: ${file(serverless.env.yml)}

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: eu-central-1
  memorySize: 128
  timeout: 10
  environment:
    TABLE_NAME: Movies
  apiGateway:
    restApiId: ${self:custom.variables.restApiId}
    restApiRootResourceId: ${self:custom.variables.restApiRootResourceId}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [MoviesTable, Arn]
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::binge-baboon-images/*"

functions:
  createMovie:
    handler: createMovie/create_movie.create
    package:
      include:
        - createMovie/**
    events:
      - http:
          path: movies
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Authorization
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.variables.authorizerId}

  getMovies:
    handler: getMovies/get_movies.get_all
    package:
      include:
        - getMovies/**
    events:
      - http:
          path: movies
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Authorization
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.variables.authorizerId}

  getMovie:
    handler: getMovie/get_movie.get_one
    package:
      include:
        - getMovie/**
    events:
      - http:
          path: movies/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Authorization
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.variables.authorizerId}

  updateMovie:
    handler: updateMovie/update_movie.update
    package:
      include:
        - updateMovie/**
    events:
      - http:
          path: movies/{id}
          method: put
          cors:
            origins:
              - '*'
            headers:
              - Authorization
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.variables.authorizerId}

  deleteMovie:
    handler: deleteMovie/delete_movie.delete
    package:
      include:
        - deleteMovie/**
    events:
      - http:
          path: movies/{id}
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Authorization
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.variables.authorizerId}

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Movies
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: title
            AttributeType: S
          - AttributeName: genres
            AttributeType: S
          - AttributeName: actors
            AttributeType: S
          - AttributeName: directors
            AttributeType: S
          - AttributeName: image_key
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: TitleIndex
            KeySchema:
              - AttributeName: title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: GenresIndex
            KeySchema:
              - AttributeName: genres
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: ActorsIndex
            KeySchema:
              - AttributeName: actors
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: DirectorsIndex
            KeySchema:
              - AttributeName: directors
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: ImageKeyIndex
            KeySchema:
              - AttributeName: image_key
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
